<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Team>
 */
class TeamFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->company(),
            'slug' => null, // Will be auto-generated by Team model
            'description' => fake()->sentence(),
            'is_active' => true,
            'required_work_hours' => 7.00,
            'default_leave_quota_days' => 12,
            'max_leave_days_per_month' => 5,
        ];
    }
}
