<?php

namespace Database\Factories;

use App\Models\Team;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Team>
 */
class TeamFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->company(),
            'slug' => null, // Will be auto-generated by Team model
            'description' => fake()->sentence(),
            'is_active' => true,
            'required_work_hours' => Team::DEFAULT_REQUIRED_WORK_HOURS,
            'default_leave_quota_days' => Team::DEFAULT_LEAVE_QUOTA_DAYS,
            'max_leave_days_per_month' => Team::DEFAULT_MAX_LEAVE_DAYS_PER_MONTH,
        ];
    }
}
